spring:
  application:
    name: conferent

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true

# 액추에이터 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

# 공통 로깅 설정
logging:
  level:
    com.conferent: INFO 