-- H2 개발환경용 더미데이터
-- application-dev.yml에서 hibernate.ddl-auto: create-drop로 설정되어 있어서
-- 애플리케이션 시작 시 자동으로 실행됩니다

-- 사용자 데이터 (BCrypt 암호화된 비밀번호 사용)
-- admin123 -> $2a$10$N.wmKMgmzYCRFQZS8/aOYeK0.VGdKGkXt8FkZsD0jH2LjF0VOP3I6
-- user123 -> $2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G
INSERT INTO users (name, email, password, role, created_at, updated_at) VALUES
('관리자', 'admin@conferent.com', '$2a$10$N.wmKMgmzYCRFQZS8/aOYeK0.VGdKGkXt8FkZsD0jH2LjF0VOP3I6', 'ADMIN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('홍길동', 'hong@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('김철수', 'kim@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('이영희', 'lee@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('박민수', 'park@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('정수진', 'jung@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('최동욱', 'choi@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('윤서연', 'yoon@conferent.com', '$2a$10$T8AvWxBgT8T6PYqY9I8nNeDqbT1HMSXnXd5THG7ZZYR.9UJ7KLW6G', 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 회의실 데이터
INSERT INTO rooms (name, location, capacity, description, created_at, updated_at) VALUES
('대회의실', '본관 3층', 20, '프레젠테이션 가능한 대형 회의실', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('소회의실 A', '본관 2층', 6, '팀 미팅용 소규모 회의실', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('소회의실 B', '본관 2층', 4, '1:1 미팅이나 화상회의용', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('브레인스토밍룸', '별관 1층', 8, '화이트보드와 포스트잇 완비', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('임원회의실', '본관 4층', 12, '고급 인테리어의 임원진 전용 회의실', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('교육실 A', '별관 2층', 15, '교육 및 세미나용', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('교육실 B', '별관 2층', 15, '교육 및 세미나용', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('미디어룸', '본관 1층', 10, '영상회의 및 미디어 시청용', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 예약 데이터 (오늘부터 일주일간)
INSERT INTO rents (start_time, end_time, purpose, description, user_id, created_at, updated_at) VALUES
-- 오늘 예약들
(CURRENT_TIMESTAMP() + INTERVAL '2' HOUR, CURRENT_TIMESTAMP() + INTERVAL '4' HOUR, '프로젝트 킥오프 미팅', '신규 프로젝트 시작을 위한 팀 미팅', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '6' HOUR, CURRENT_TIMESTAMP() + INTERVAL '7' HOUR, '고객 미팅', '신규 고객사 제안 미팅', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '9' HOUR, CURRENT_TIMESTAMP() + INTERVAL '10' HOUR, '일일 스크럼', '팀 일일 스크럼 미팅', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 내일 예약들
(CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '10' HOUR, CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '12' HOUR, '스프린트 리뷰', '2주차 스프린트 리뷰 미팅', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '14' HOUR, CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '15' HOUR, '1:1 면담', '팀원 개별 면담', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '16' HOUR, CURRENT_TIMESTAMP() + INTERVAL '1' DAY + INTERVAL '18' HOUR, '기획 회의', '신규 서비스 기획 회의', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 모레 예약들
(CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '9' HOUR, CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '11' HOUR, '교육 세션', '신입사원 교육', 6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '13' HOUR, CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '14' HOUR, '브레인스토밍', '아이디어 브레인스토밍', 7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '15' HOUR, CURRENT_TIMESTAMP() + INTERVAL '2' DAY + INTERVAL '17' HOUR, '코드 리뷰', '주간 코드 리뷰', 8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 3일 후 예약들
(CURRENT_TIMESTAMP() + INTERVAL '3' DAY + INTERVAL '10' HOUR, CURRENT_TIMESTAMP() + INTERVAL '3' DAY + INTERVAL '12' HOUR, '월간 회고', '팀 월간 회고 미팅', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '3' DAY + INTERVAL '14' HOUR, CURRENT_TIMESTAMP() + INTERVAL '3' DAY + INTERVAL '16' HOUR, '기술 세미나', '신기술 도입 세미나', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 4일 후 예약들
(CURRENT_TIMESTAMP() + INTERVAL '4' DAY + INTERVAL '9' HOUR, CURRENT_TIMESTAMP() + INTERVAL '4' DAY + INTERVAL '11' HOUR, '고객사 미팅', '기존 고객사 정기 미팅', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '4' DAY + INTERVAL '13' HOUR, CURRENT_TIMESTAMP() + INTERVAL '4' DAY + INTERVAL '15' HOUR, '디자인 리뷰', 'UI/UX 디자인 리뷰', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 5일 후 예약들
(CURRENT_TIMESTAMP() + INTERVAL '5' DAY + INTERVAL '10' HOUR, CURRENT_TIMESTAMP() + INTERVAL '5' DAY + INTERVAL '12' HOUR, '분기별 회의', 'Q1 분기별 성과 회의', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '5' DAY + INTERVAL '14' HOUR, CURRENT_TIMESTAMP() + INTERVAL '5' DAY + INTERVAL '16' HOUR, '팀 빌딩', '팀 빌딩 활동', 6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 6일 후 예약들
(CURRENT_TIMESTAMP() + INTERVAL '6' DAY + INTERVAL '9' HOUR, CURRENT_TIMESTAMP() + INTERVAL '6' DAY + INTERVAL '11' HOUR, '보안 교육', '정보보안 교육', 7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(CURRENT_TIMESTAMP() + INTERVAL '6' DAY + INTERVAL '13' HOUR, CURRENT_TIMESTAMP() + INTERVAL '6' DAY + INTERVAL '15' HOUR, '프로젝트 마감', '프로젝트 마감 회의', 8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 회의실-예약 연결 데이터 (RoomRent)
INSERT INTO room_rents (room_id, rent_id, created_at) VALUES
-- 오늘 예약들
(1, 1, CURRENT_TIMESTAMP()), -- 대회의실 - 프로젝트 킥오프
(2, 2, CURRENT_TIMESTAMP()), -- 소회의실 A - 고객 미팅
(3, 3, CURRENT_TIMESTAMP()), -- 소회의실 B - 일일 스크럼

-- 내일 예약들
(1, 4, CURRENT_TIMESTAMP()), -- 대회의실 - 스프린트 리뷰
(3, 5, CURRENT_TIMESTAMP()), -- 소회의실 B - 1:1 면담
(4, 6, CURRENT_TIMESTAMP()), -- 브레인스토밍룸 - 기획 회의

-- 모레 예약들
(6, 7, CURRENT_TIMESTAMP()), -- 교육실 A - 교육 세션
(4, 8, CURRENT_TIMESTAMP()), -- 브레인스토밍룸 - 브레인스토밍
(2, 9, CURRENT_TIMESTAMP()), -- 소회의실 A - 코드 리뷰

-- 3일 후 예약들
(1, 10, CURRENT_TIMESTAMP()), -- 대회의실 - 월간 회고
(6, 11, CURRENT_TIMESTAMP()), -- 교육실 A - 기술 세미나

-- 4일 후 예약들
(2, 12, CURRENT_TIMESTAMP()), -- 소회의실 A - 고객사 미팅
(5, 13, CURRENT_TIMESTAMP()), -- 임원회의실 - 디자인 리뷰

-- 5일 후 예약들
(1, 14, CURRENT_TIMESTAMP()), -- 대회의실 - 분기별 회의
(7, 15, CURRENT_TIMESTAMP()), -- 교육실 B - 팀 빌딩

-- 6일 후 예약들
(6, 16, CURRENT_TIMESTAMP()), -- 교육실 A - 보안 교육
(1, 17, CURRENT_TIMESTAMP()); -- 대회의실 - 프로젝트 마감

-- 사용자 초대 데이터 (UserInvite)
INSERT INTO user_invites (user_id, room_rent_id, status, invited_at, responded_at, created_at, updated_at) VALUES
-- 프로젝트 킥오프 미팅 초대 (대회의실)
(3, 1, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' HOUR, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 1, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '30' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 1, 'PENDING', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 1, 'DECLINED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '2' HOUR, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 고객 미팅 초대 (소회의실 A)
(2, 2, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '15' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 2, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '20' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 스프린트 리뷰 초대 (대회의실)
(2, 4, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' HOUR, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 4, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '45' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 4, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '30' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 4, 'PENDING', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 기획 회의 초대 (브레인스토밍룸)
(2, 6, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' HOUR, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 6, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '30' MINUTE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 6, 'PENDING', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 6, 'PENDING', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 교육 세션 초대 (교육실 A)
(2, 7, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 7, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 7, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 7, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- 분기별 회의 초대 (대회의실)
(2, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 14, 'ACCEPTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + INTERVAL '1' DAY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(8, 14, 'PENDING', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()); 